package jp.flutter.app

import android.content.Context
import io.objectbox.BoxStore

// This class is normally generated by ObjectBox based on objectbox-model.json
// For this example we include a minimal placeholder.
object MyObjectBox {
    fun builder(): BoxStore.Builder = BoxStore.builder()
}
