name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 7.4.1
  dart_style: 3.1.1

dependencies:
  async: 2.13.0
  dartx: 1.2.0
  flutter:
    sdk: flutter
  get_it: 7.6.7
  injectable: 2.5.0
  meta: 1.16.0
  resources:
    path: ../resources
  rxdart: 0.27.7
  shared:
    path: ../shared
  tuple: 2.0.2

dev_dependencies:
  build_runner: 2.5.4
  custom_lint: 0.6.0
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.8
  freezed_annotation: 2.4.4
  injectable_generator: 2.7.0
  logging: 1.3.0
  mocktail: 1.0.3
  nals_lints:
    path: ../nals_lints
