name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependency_overrides:
  analyzer: 7.4.1
  dart_style: 3.1.1
  js: ^0.7.0
dependencies:
  async: 2.13.0
  auto_route: 10.1.0+1
  cached_network_image: 3.3.1
  cupertino_icons: 1.0.6
  dartx: 1.2.0
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.4
  flutter_local_notifications: 19.3.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.9.0
  flutter_svg: 2.0.9
  get_it: 7.6.7
  infinite_scroll_pagination: 4.0.0
  initializer:
    path: ../initializer
  injectable: 2.5.0
  pincode_input_fields: ^1.0.3
  pinput: ^5.0.1
  resources:
    path: ../resources
  rxdart: 0.27.7
  shared:
    path: ../shared
  tuple: 2.0.2
dev_dependencies:
  auto_route_generator: 10.2.3
  bloc_test: 9.1.6
  build_runner: 2.5.4
  custom_lint: 0.6.0
  flutter_gen_runner: 5.11.0
  flutter_launcher_icons: 0.13.1
  flutter_lints: 5.0.0
  flutter_native_splash: 2.3.11
  flutter_test:
    sdk: flutter
  freezed: 2.5.8
  freezed_annotation: 2.4.4
  injectable_generator: 2.7.0
  logging: 1.3.0
  mocktail: 1.0.3
  nals_lints:
    path: ../nals_lints

# Config generate when build
flutter_gen:
  output: lib/resource/generated
  line_length: 160
  #null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true
  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/color/colors.xml
flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: nunitosans
      fonts:
        - asset: assets/fonts/NunitoSans_10pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans_10pt-ExtraBold.ttf
        - asset: assets/fonts/NunitoSans_7pt-Light.ttf
          weight: 200
        - asset: assets/fonts/NunitoSans_10pt-SemiBold.ttf
        - asset: assets/fonts/NunitoSans_10pt-Medium.ttf
        - asset: assets/fonts/NunitoSans_10pt-Bold.ttf
          weight: 800
    - family: ntr
      fonts:
        - asset: assets/fonts/NTR-Regular.ttf
          weight: 400
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
#    - family: Muli
#      fonts:
#        - asset: assets/fonts/Muli-Bold.ttf
#          weight: 900
#        - asset: assets/fonts/Muli-SemiBold.ttf
#          weight: 700
#        - asset: assets/fonts/Muli-Regular.ttf
#          weight: 400
