name: shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 7.4.1
  dart_style: 3.1.1

dependencies:
  android_id: 0.3.6
  async: 2.13.0
  dartx: 1.2.0
  decimal: 2.3.3
  device_info_plus: 9.1.2
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.3.1
  flutter_udid: 3.0.0
  injectable: 2.5.0
  intl: 0.20.2
  mime: 1.0.5
  package_info_plus: 8.3.0
  path_provider: 2.1.2
  rxdart: 0.27.7
  timezone: 0.10.1
  url_launcher: 6.2.4

dev_dependencies:
  build_runner: 2.5.4
  custom_lint: 0.6.0
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.8
  freezed_annotation: 2.4.4
  injectable_generator: 2.7.0
  logging: 1.3.0
  mocktail: 1.0.3
  nals_lints:
    path: ../nals_lints
